---
apiVersion: v1
kind: ConfigMap
metadata:
  name: palworld-cm
data:
  PUID: "1000"
  PGID: "1000"
  PORT: "8211"
  PLAYERS: "6"
  SERVER_PASSWORD: "worldofpals" # TODO Make it more secure => Maybe Vault ??
  MULTITHREADING: "true"
  RCON_ENABLED: "true"
  RCON_PORT: "25575"
  TZ: UTC
  COMMUNITY: "false"
  SERVER_NAME: "Fan Bois"
  SERVER_DESCRIPTION: "Best palworld server on K8s"